-- # Write your MySQL query statement below
SELECT A.EMPLOYEE_ID, B.TEAM_SIZE 
FROM EMPLOYEE A
INNER JOIN (
  SELECT TEAM_ID, COUNT(*) AS TEAM_SIZE
  FROM EMPLOYEE
  GROUP BY TEAM_ID) B
ON A.TEAM_ID = B.TEAM_ID;