-- # Write your MySQL query statement below
SELECT GENDER, 
       DAY, 
       SUM(SCORE_POINTS) OVER (PARTITION BY GENDER ORDER BY DAY) AS TOTAL
FROM SCORES
GROUP BY GENDER, DAY
ORDER BY GENDER ASC, DAY ASC;