-- # Write your MySQL query statement below
WITH TARGET AS (
  SELECT A.PROJECT_ID, A.EMPLOYEE_ID,
       RANK() OVER (PARTITION BY A.PROJECT_ID ORDER BY EXPERIENCE_YEARS DESC) AS RANK_NUMBER  
  FROM PROJECT A
  INNER JOIN EMPLOYEE B
  ON A.EMPLOYEE_ID = B.EMPLOYEE_ID)
SELECT PROJECT_ID, EMPLOYEE_ID
FROM TARGET
WHERE RANK_NUMBER = 1;