-- # Write your MySQL query statement below
WITH TARGET AS (
SELECT A.CUSTOMER_ID, C.PRODUCT_ID, C.PRODUCT_NAME,
  RANK() OVER(PARTITION BY A.CUSTOMER_ID ORDER BY COUNT(*) DESC) AS RANKING
FROM CUSTOMERS A
INNER JOIN ORDERS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
INNER JOIN PRODUCTS C
ON B.PRODUCT_ID = C.PRODUCT_ID
GROUP BY A.CUSTOMER_ID, C.PRODUCT_ID)

SELECT CUSTOMER_ID, PRODUCT_ID, PRODUCT_NAME
FROM TARGET
WHERE RANKING = 1;