-- # Write your MySQL query statement below
WITH TARGET AS (
  SELECT A.PRODUCT_NAME, A.PRODUCT_ID, B.ORDER_ID, B.ORDER_DATE,
       RANK() OVER (PARTITION BY A.PRODUCT_NAME ORDER BY B.ORDER_DATE DESC) AS RANKING
  FROM PRODUCTS A
  INNER JOIN ORDERS B
  ON A.PRODUCT_ID = B.PRODUCT_ID
  ORDER BY A.PRODUCT_NAME ASC, A.PRODUCT_ID ASC, B.ORDER_ID ASC)

SELECT PRODUCT_NAME, PRODUCT_ID, ORDER_ID, ORDER_DATE
FROM TARGET
WHERE RANKING = 1;